### ISSUE TITLE
logout redirects to error page

### ISSUE THREAD

**Issue by notefox** [Ktechen/Dripbox#59]
the logout path isn't implemented correctly in the header

example:
 when clicking on "Logout" in the header, while looking at a file on Dashboard, the page gets redirected to "https://dripbox.herokuapp.com/dashboard/logout" which is not the correct redirect

**Comment by notefox** [comment]
https://dripbox.herokuapp.com/dashboard/3 -> clicking logout button -> https://dripbox.herokuapp.com/dashboard/logout

**Comment by MathisHTW** [comment]
pr from yesterday (fix/header logout button) should resolve the issue
